# Fehlerschätzer
# https://wias-pdelib.github.io/ExtendableFEM.jl/stable/module_examples/Example210_LshapeAdaptivePoissonProblem/

module Example_Stokes

using ExtendableFEM
using ExtendableGrids
using GridVisualize
using CairoMakie
using Symbolics

default_plotter!(CairoMakie)

nu = 10^(-1)

#=
function f!(result, qpinfo)
    x = qpinfo.x[1]
    y = qpinfo.x[2]
    ddu1 = -4 * (2 * y - 1) * (3 * x^4 - 6 * x^3 + 3 * x^2 * (2 * y^2 - 2 * y + 1) + (1 - 6 * x) * (y - 1) * y)
    ddu2 = 4 * (2 * x - 1) * ((x - 1) * x * (6 * y^2 - 6 * y + 1) + 3 * (y - 1)^2 * y^2)
    dp1 = 5 * x^4
    dp2 = 5 * y^4
    result[1] = -nu * ddu1 + dp1
    result[2] = -nu * ddu2 + dp2
    return nothing
end
=#

using Symbolics

# exact data for problem generated by Symbolics
function prepare_data(; μ=1)

    @variables x y

    # stream function ξ
    ξ = -sin(2 * pi * x) * cos(2 * pi * y)

    # velocity u = curl ξ
    ∇ξ = Symbolics.gradient(ξ, [x, y])
    u = [-∇ξ[2], ∇ξ[1]]

    # pressure
    p = (cos(4 * pi * x) - cos(4 * pi * y)) / 4 # Im paper schauen, dass int = 0 ist

    # gradient of velocity
    ∇u = Symbolics.jacobian(u, [x, y])
    ∇u_reshaped = [∇u[1, 1], ∇u[1, 2], ∇u[2, 1], ∇u[2, 2]]

    # Laplacian
    Δu = [
        (Symbolics.gradient(∇u[1, 1], [x])+Symbolics.gradient(∇u[1, 2], [y]))[1],
        (Symbolics.gradient(∇u[2, 1], [x])+Symbolics.gradient(∇u[2, 2], [y]))[1],
    ]

    # right-hand side
    f = -μ * Δu + Symbolics.gradient(p, [x, y])

    # build functions
    p_eval = build_function(p, x, y, expression=Val{false})
    u_eval = build_function(u, x, y, expression=Val{false})
    ∇u_eval = build_function(∇u_reshaped, x, y, expression=Val{false})
    f_eval = build_function(f, x, y, expression=Val{false})

    return f_eval[2], u_eval[2], ∇u_eval[2], p_eval
end

function g!(result, _)
    result[1] = 0
    return nothing
end

μ = 0.1 # viscosity parameter
function kernel!(result, input, qpinfo)
    ∇u, p = view(input, 1:4), view(input, 5)
    result[1] = μ * ∇u[1] - p[1]
    result[2] = μ * ∇u[2]
    result[3] = μ * ∇u[3]
    result[4] = μ * ∇u[4] - p[1]
    result[5] = -(∇u[1] + ∇u[4])
    return nothing
end

function main(; Plotter=default_plotter(), nrefs=6, kwargs...)
    # prepare problem data
    f_eval, u_eval, ∇u_eval, p_eval = prepare_data(; μ=μ)
    rhs!(result, qpinfo) = (f_eval(result, qpinfo.x[1], qpinfo.x[2]))
    exact_p!(result, qpinfo) = (result[1] = p_eval(qpinfo.x[1], qpinfo.x[2]))
    exact_u!(result, qpinfo) = (u_eval(result, qpinfo.x[1], qpinfo.x[2]))
    exact_∇u!(result, qpinfo) = (∇u_eval(result, qpinfo.x[1], qpinfo.x[2]))

    # generate two problems definitions
    # one for velocity, one for pressure
    u = Unknown("u", name="velocity", symbol_ansatz="u", symbol_test="v", dim=2)
    p = Unknown("p", name="pressure", symbol_ansatz="p", symbol_test="q", dim=2)

    PD = ProblemDescription("Stokes problem")
    assign_unknown!(PD, u)
    assign_unknown!(PD, p)

    assign_operator!(PD, BilinearOperator(kernel!, [grad(u), id(p)]))
    assign_operator!(PD, LinearOperator(rhs!, [id(u)]))
    assign_operator!(PD, InterpolateBoundaryData(u, exact_u!; regions=1:4, bonus_quadorder=2))
    assign_restriction!(PD, ZeroMeanValueRestriction(p))
    #assign_operator!(PD, HomogeneousBoundaryData(u; regions=1:4))


    #=
    PDu = ProblemDescription("Stokes IPM - velocity update")
    assign_unknown!(PDu, u)
    assign_operator!(PDu, BilinearOperator([grad(u)]; factor=nu, store=true, kwargs...))
    assign_operator!(PDu, LinearOperator([div(u)], [id(p)]; factor=-1, store=true, kwargs...))
    assign_operator!(PDu, LinearOperator(f!, [id(u)]; kwargs...))
    assign_operator!(PDu, HomogeneousBoundaryData(u; regions=1:4))

    PDp = ProblemDescription("Stokes IPM - pressure update")
    assign_unknown!(PDp, p)
    assign_operator!(PDp, LinearOperator([id(p)], [div(u)]; store=true, kwargs...))
    assign_operator!(PDp, LinearOperator(g!, [id(p)]; kwargs...))
    =#

    # create grid
    xgrid = uniform_refine(grid_unitsquare(Triangle2D), nrefs)

    # create P2/P1 pair
    FETypes = (H1P2{2,2}, H1P1{1})
    # https://wias-pdelib.github.io/ExtendableFEM.jl/stable/module_examples/Example252_NSEPlanarLatticeFlow/

    # Fehlerschätzer
    # https://wias-pdelib.github.io/ExtendableFEM.jl/stable/module_examples/Example210_LshapeAdaptivePoissonProblem/

    # solve problem
    FES = [FESpace{FETypes[1]}(xgrid), FESpace{FETypes[2]}(xgrid)]
    sol = solve(PD, FES) #FEVector(FES, tags=[u, p])
    #=
    SC1 = SolverConfiguration(PDu; init=sol, maxiterations=1, target_residual=1.0e-8, constant_matrix=true, kwargs...)
    SC2 = SolverConfiguration(PDp; init=sol, maxiterations=1, target_residual=1.0e-1, constant_matrix=true, kwargs...)
    sol, nits = iterate_until_stationarity([SC1, SC2]; init=sol, kwargs...)
    @info "converged after $nits iterations"
    =#

    # plot
    plt = ExtendableFEM.plot([id(u), id(p)], sol; Plotter=Plotter, show=true)
    # ExtendableFEM.save("test.png", plt) 

    # prepare error calculations
    function exact_error!(result, u, qpinfo)
        exact_u!(view(result, 1:2), qpinfo)
        exact_∇u!(view(result, 3:6), qpinfo)
        result .-= u
        return result .= result .^ 2
    end
    function exact_error_p!(result, p, qpinfo)
        exact_p!(view(result, 1), qpinfo)
        result .-= p
        return result .= result .^ 2
    end
    ErrorIntegratorExact = ItemIntegrator(exact_error!, [id(u), grad(u)]; quadorder=2 * (2 + 1))
    ErrorIntegratorPressure = ItemIntegrator(exact_error_p!, [id(p)]; quadorder=2 * (2 + 1))

    error = evaluate(ErrorIntegratorExact, sol)
    L2errorU = sqrt(sum(view(error, 1, :)) + sum(view(error, 2, :)))
    H1errorU = sqrt(sum(view(error, 3, :)) + sum(view(error, 4, :)) + sum(view(error, 5, :)) + sum(view(error, 6, :)))
    @info "L2error(u) = $L2errorU"
    @info "L2error(∇u) = $H1errorU"
    evaluate!(error, ErrorIntegratorPressure, sol)
    L2errorP = sqrt(sum(view(error, 1, :)))
    @info "L2error(p) = $L2errorP"

    return sol, plt
end

end